// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Function is an autogenerated mock type for the Function type
type Function struct {
	mock.Mock
}

// SendMail provides a mock function with given fields: email, token
func (_m *Function) SendMail(email string, token string) (string, error) {
	ret := _m.Called(email, token)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(email, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFunction interface {
	mock.TestingT
	Cleanup(func())
}

// NewFunction creates a new instance of Function. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFunction(t mockConstructorTestingTNewFunction) *Function {
	mock := &Function{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
