// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	bookmarks "charum/business/bookmarks"
	dtobookmarks "charum/dto/bookmarks"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// CountByThreadID provides a mock function with given fields: threadID
func (_m *UseCase) CountByThreadID(threadID primitive.ObjectID) (int, error) {
	ret := _m.Called(threadID)

	var r0 int
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) int); ok {
		r0 = rf(threadID)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(primitive.ObjectID) error); ok {
		r1 = rf(threadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: domain
func (_m *UseCase) Create(domain *bookmarks.Domain) (bookmarks.Domain, error) {
	ret := _m.Called(domain)

	var r0 bookmarks.Domain
	if rf, ok := ret.Get(0).(func(*bookmarks.Domain) bookmarks.Domain); ok {
		r0 = rf(domain)
	} else {
		r0 = ret.Get(0).(bookmarks.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*bookmarks.Domain) error); ok {
		r1 = rf(domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: domain
func (_m *UseCase) Delete(domain *bookmarks.Domain) (bookmarks.Domain, error) {
	ret := _m.Called(domain)

	var r0 bookmarks.Domain
	if rf, ok := ret.Get(0).(func(*bookmarks.Domain) bookmarks.Domain); ok {
		r0 = rf(domain)
	} else {
		r0 = ret.Get(0).(bookmarks.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*bookmarks.Domain) error); ok {
		r1 = rf(domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAllByThreadID provides a mock function with given fields: threadID
func (_m *UseCase) DeleteAllByThreadID(threadID primitive.ObjectID) error {
	ret := _m.Called(threadID)

	var r0 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) error); ok {
		r0 = rf(threadID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAllByUserID provides a mock function with given fields: userID
func (_m *UseCase) DeleteAllByUserID(userID primitive.ObjectID) error {
	ret := _m.Called(userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DomainToResponse provides a mock function with given fields: domain
func (_m *UseCase) DomainToResponse(domain bookmarks.Domain) (dtobookmarks.Response, error) {
	ret := _m.Called(domain)

	var r0 dtobookmarks.Response
	if rf, ok := ret.Get(0).(func(bookmarks.Domain) dtobookmarks.Response); ok {
		r0 = rf(domain)
	} else {
		r0 = ret.Get(0).(dtobookmarks.Response)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(bookmarks.Domain) error); ok {
		r1 = rf(domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DomainsToResponseArray provides a mock function with given fields: domains
func (_m *UseCase) DomainsToResponseArray(domains []bookmarks.Domain) ([]dtobookmarks.Response, error) {
	ret := _m.Called(domains)

	var r0 []dtobookmarks.Response
	if rf, ok := ret.Get(0).(func([]bookmarks.Domain) []dtobookmarks.Response); ok {
		r0 = rf(domains)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtobookmarks.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]bookmarks.Domain) error); ok {
		r1 = rf(domains)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllByUserID provides a mock function with given fields: userID
func (_m *UseCase) GetAllByUserID(userID primitive.ObjectID) ([]bookmarks.Domain, error) {
	ret := _m.Called(userID)

	var r0 []bookmarks.Domain
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) []bookmarks.Domain); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bookmarks.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(primitive.ObjectID) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCase(t mockConstructorTestingTNewUseCase) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
