// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"

	threads "charum/business/threads"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: creatorID, topicName, domain
func (_m *UseCase) Create(creatorID primitive.ObjectID, topicName string, domain *threads.Domain) (threads.Domain, error) {
	ret := _m.Called(creatorID, topicName, domain)

	var r0 threads.Domain
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, string, *threads.Domain) threads.Domain); ok {
		r0 = rf(creatorID, topicName, domain)
	} else {
		r0 = ret.Get(0).(threads.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(primitive.ObjectID, string, *threads.Domain) error); ok {
		r1 = rf(creatorID, topicName, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: creatorID, threadID
func (_m *UseCase) Delete(creatorID primitive.ObjectID, threadID primitive.ObjectID) (threads.Domain, error) {
	ret := _m.Called(creatorID, threadID)

	var r0 threads.Domain
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, primitive.ObjectID) threads.Domain); ok {
		r0 = rf(creatorID, threadID)
	} else {
		r0 = ret.Get(0).(threads.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(primitive.ObjectID, primitive.ObjectID) error); ok {
		r1 = rf(creatorID, threadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *UseCase) GetByID(id primitive.ObjectID) (threads.Domain, error) {
	ret := _m.Called(id)

	var r0 threads.Domain
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) threads.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(threads.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(primitive.ObjectID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWithSortAndOrder provides a mock function with given fields: page, limit, sort, order
func (_m *UseCase) GetWithSortAndOrder(page int, limit int, sort string, order string) ([]threads.Domain, int, error) {
	ret := _m.Called(page, limit, sort, order)

	var r0 []threads.Domain
	if rf, ok := ret.Get(0).(func(int, int, string, string) []threads.Domain); ok {
		r0 = rf(page, limit, sort, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]threads.Domain)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(int, int, string, string) int); ok {
		r1 = rf(page, limit, sort, order)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(int, int, string, string) error); ok {
		r2 = rf(page, limit, sort, order)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: creatorID, threadID, topicName, domain
func (_m *UseCase) Update(creatorID primitive.ObjectID, threadID primitive.ObjectID, topicName string, domain *threads.Domain) (threads.Domain, error) {
	ret := _m.Called(creatorID, threadID, topicName, domain)

	var r0 threads.Domain
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, primitive.ObjectID, string, *threads.Domain) threads.Domain); ok {
		r0 = rf(creatorID, threadID, topicName, domain)
	} else {
		r0 = ret.Get(0).(threads.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(primitive.ObjectID, primitive.ObjectID, string, *threads.Domain) error); ok {
		r1 = rf(creatorID, threadID, topicName, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCase(t mockConstructorTestingTNewUseCase) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
